from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot training/validation curves from history.json")
    parser.add_argument(
        "--history",
        default="artifacts/student_stage2_text_align_quick/history.json",
        help="Path to history.json generated by distillation training.",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output image path. Defaults to <history_dir>/training_curves.png",
    )
    return parser.parse_args()


def _series(history: list[dict], key: str) -> tuple[list[int], list[float]]:
    xs: list[int] = []
    ys: list[float] = []
    for row in history:
        if key in row:
            xs.append(int(row["epoch"]))
            ys.append(float(row[key]))
    return xs, ys


def _plot_if_present(ax, history: list[dict], key: str, label: str) -> None:
    xs, ys = _series(history, key)
    if xs:
        ax.plot(xs, ys, marker="o", linewidth=1.5, markersize=3, label=label)


def main() -> None:
    args = parse_args()
    history_path = Path(args.history)
    if not history_path.exists():
        raise FileNotFoundError(f"History not found: {history_path}")

    history = json.loads(history_path.read_text(encoding="utf-8"))
    if not history:
        raise ValueError("History is empty, nothing to plot.")

    output_path = Path(args.output) if args.output else history_path.parent / "training_curves.png"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    plt.style.use("seaborn-v0_8-whitegrid")
    fig, axes = plt.subplots(3, 1, figsize=(12, 14), constrained_layout=True)

    ax = axes[0]
    _plot_if_present(ax, history, "total_loss", "train total_loss")
    _plot_if_present(ax, history, "val_total_loss", "val total_loss")
    _plot_if_present(ax, history, "distill_loss", "train distill_loss")
    _plot_if_present(ax, history, "val_distill_loss", "val distill_loss")
    ax.set_title("Training and Validation Loss")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Loss")
    ax.legend(loc="best")

    ax = axes[1]
    _plot_if_present(ax, history, "contrastive_loss", "contrastive")
    _plot_if_present(ax, history, "relation_distill_loss", "relation")
    _plot_if_present(ax, history, "crd_loss", "crd")
    _plot_if_present(ax, history, "icl_loss", "icl")
    _plot_if_present(ax, history, "feature_distill_loss", "feature")
    _plot_if_present(ax, history, "masked_feature_distill_loss", "masked_feature")
    _plot_if_present(ax, history, "gradient_distill_loss", "gradient")
    _plot_if_present(ax, history, "augmented_feature_distill_loss", "augmented_feature")
    ax.set_title("Important Distillation Components")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Component Loss")
    ax.legend(loc="best")

    ax = axes[2]
    _plot_if_present(ax, history, "contrastive_weight", "contrastive_w")
    _plot_if_present(ax, history, "distill_weight", "distill_w")
    _plot_if_present(ax, history, "relation_distill_weight", "relation_w")
    _plot_if_present(ax, history, "crd_weight", "crd_w")
    _plot_if_present(ax, history, "icl_weight", "icl_w")
    _plot_if_present(ax, history, "feature_distill_weight", "feature_w")
    _plot_if_present(ax, history, "masked_feature_distill_weight", "masked_feature_w")
    _plot_if_present(ax, history, "gradient_distill_weight", "gradient_w")
    _plot_if_present(ax, history, "augmented_feature_distill_weight", "augmented_feature_w")

    ax2 = ax.twinx()
    _plot_if_present(ax2, history, "lr", "lr")
    _plot_if_present(ax2, history, "contrastive_temperature", "temperature")
    ax.set_title("Key Weights and Optimization Parameters")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Weight")
    ax2.set_ylabel("LR / Temperature")

    lines_1, labels_1 = ax.get_legend_handles_labels()
    lines_2, labels_2 = ax2.get_legend_handles_labels()
    ax.legend(lines_1 + lines_2, labels_1 + labels_2, loc="best")

    fig.savefig(output_path, dpi=180)
    print(f"Saved plot to: {output_path}")


if __name__ == "__main__":
    main()
