[project]
name = "2026lpcvc-track1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "onnxscript>=0.6.2",
    "pandas>=2.2.3",
    "open-clip-torch>=2.32.0",
    "pillow>=11.0.0",
    "scikit-learn>=1.7.2",
    "setuptools==81.0.0",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
    "transformers>=4.57.6",
]

[project.optional-dependencies]
qai = [
    "qai-hub>=0.45.0",
    "qai-hub-models>=0.46.1",
]
